/*
 * Copyright (C) 2019 Natalie
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package controlpi;

import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author Natalie
 */
public class ControlPiTest {
    
    public ControlPiTest() {
    }

    @Test
    public void testGetData() {
        
    }
    
    @Test
    public void testGetCurrentData() {
        
    }
    
    @Test
    public void testGetCurrentDataBad() {}
    
    @Test
    public void testInputOptimalConditionsOnTemp() {}
    
    @Test
    public void testInputOptimalConditionsOnHumidity() {}
    
    @Test
    public void testInputOptimalConditionsOnLight() {}
    
    @Test
    public void testInputOptimalConditionsOnWaterTime() {}
    
    @Test
    public void testInputOptimalConditionsOnWaterTimeInterval() {}
    
    @Test
    public void testLoginUsernameValid() {}
    
    @Test
    public void testLoginUsernameInvalid() {}
    
    @Test
    public void testLoginPasswordValid() {}
    
    @Test
    public void testLoginPasswordInvalid() {}
}
