package gem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nirda
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelA = new javax.swing.JPanel();
        PanelB = new javax.swing.JPanel();
        CurrentConditionsLabel = new javax.swing.JLabel();
        TempLabel = new javax.swing.JLabel();
        HumidityLabel = new javax.swing.JLabel();
        LightLabel = new javax.swing.JLabel();
        WaterLabel = new javax.swing.JLabel();
        LiveFeedPanel = new javax.swing.JPanel();
        LiveFeedLabel = new javax.swing.JLabel();
        CurrentTempLabel = new javax.swing.JLabel();
        CurrentHumidityLabel = new javax.swing.JLabel();
        CurrentLightLabel = new javax.swing.JLabel();
        CurrentWaterLabel = new javax.swing.JLabel();
        PanelC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ChangeOptimalButton = new javax.swing.JButton();
        CreateReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CurrentConditionsLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        CurrentConditionsLabel.setText("Current Conditons ");

        TempLabel.setText("Temperature (°C) :");

        HumidityLabel.setText("Humidity:");

        LightLabel.setText("Hours of Light: ");

        WaterLabel.setText("Time Last Watered:");

        LiveFeedPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout LiveFeedPanelLayout = new javax.swing.GroupLayout(LiveFeedPanel);
        LiveFeedPanel.setLayout(LiveFeedPanelLayout);
        LiveFeedPanelLayout.setHorizontalGroup(
            LiveFeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LiveFeedPanelLayout.setVerticalGroup(
            LiveFeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        LiveFeedLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        LiveFeedLabel.setText("Live Feed");

        CurrentTempLabel.setText("jLabel2");

        CurrentHumidityLabel.setText("jLabel3");

        CurrentLightLabel.setText("jLabel4");

        CurrentWaterLabel.setText("jLabel5");

        javax.swing.GroupLayout PanelBLayout = new javax.swing.GroupLayout(PanelB);
        PanelB.setLayout(PanelBLayout);
        PanelBLayout.setHorizontalGroup(
            PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LiveFeedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelBLayout.createSequentialGroup()
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(CurrentConditionsLabel))
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HumidityLabel)
                            .addComponent(TempLabel)
                            .addComponent(LightLabel)
                            .addComponent(WaterLabel))
                        .addGap(18, 18, 18)
                        .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CurrentTempLabel)
                            .addComponent(CurrentHumidityLabel)
                            .addComponent(CurrentLightLabel)
                            .addComponent(CurrentWaterLabel)))
                    .addGroup(PanelBLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(LiveFeedLabel)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        PanelBLayout.setVerticalGroup(
            PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CurrentConditionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TempLabel)
                    .addComponent(CurrentTempLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumidityLabel)
                    .addComponent(CurrentHumidityLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LightLabel)
                    .addComponent(CurrentLightLabel))
                .addGap(18, 18, 18)
                .addGroup(PanelBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaterLabel)
                    .addComponent(CurrentWaterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(LiveFeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LiveFeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setText("Add Later");

        ChangeOptimalButton.setText("Change Optimal Conditons");
        ChangeOptimalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeOptimalButtonActionPerformed(evt);
            }
        });

        CreateReportButton.setText("Create Report");
        CreateReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCLayout = new javax.swing.GroupLayout(PanelC);
        PanelC.setLayout(PanelCLayout);
        PanelCLayout.setHorizontalGroup(
            PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CreateReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChangeOptimalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelCLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        PanelCLayout.setVerticalGroup(
            PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addComponent(ChangeOptimalButton)
                .addGap(28, 28, 28)
                .addComponent(CreateReportButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelALayout = new javax.swing.GroupLayout(PanelA);
        PanelA.setLayout(PanelALayout);
        PanelALayout.setHorizontalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelALayout.createSequentialGroup()
                .addComponent(PanelB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelALayout.setVerticalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void CreateReportButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void ChangeOptimalButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        dispose();
        new OptimalConditions().setVisible(true);
    }                                                   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void updateCurrent(double t, double h, int l, int w) throws SQLException 
    {
        double idealTemp = 0.0;
        double idealHumidity = 0.0;
        int idealLight = 0;
        int idealWater = 0;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gem","root","Nirda21!ali");
            Statement st = con.createStatement();
            
            ResultSet rs1 = st.executeQuery("SELECT temp FROM optimal");
            while(rs1.next())
            {
                String idealTempStr = rs1.getString("temp");
                idealTemp = Float.parseFloat(idealTempStr);
            }
            
            ResultSet rs2 = st.executeQuery("SELECT humidity FROM optimal");
            while(rs2.next())
            {
                String idealHumidityStr = rs1.getString("humidity");
                idealHumidity = Float.parseFloat(idealHumidityStr);
            }
            
            ResultSet rs3 = st.executeQuery("SELECT light FROM optimal");
            while(rs3.next())
            {
                String idealLightStr = rs1.getString("light");
                idealLight = Integer.parseInt(idealLightStr);
            }
            
            ResultSet rs4 = st.executeQuery("SELECT water FROM optimal");
            while(rs4.next())
            {
                String idealWaterStr = rs1.getString("water");
                idealWater = Integer.parseInt(idealWaterStr);
            }
            
            
            if(t<idealTemp)
            {
                CurrentTempLabel.setText(String.valueOf(t));
                CurrentTempLabel.setForeground(Color.green);
            }else{
                CurrentTempLabel.setText(String.valueOf(t));
                CurrentTempLabel.setForeground(Color.red);
            }
            
            if(h<idealHumidity)
            {
                CurrentHumidityLabel.setText(String.valueOf(h));
                CurrentHumidityLabel.setForeground(Color.green);
            }else{
                CurrentHumidityLabel.setText(String.valueOf(h));
                CurrentHumidityLabel.setForeground(Color.red);
            }
            
            if(l<idealLight)
            { 
                CurrentLightLabel.setText(String.valueOf(l));
                CurrentLightLabel.setForeground(Color.green);
            }else{
                CurrentLightLabel.setText(String.valueOf(l));
                CurrentLightLabel.setForeground(Color.red);
            }
            
            if(w<idealWater)
            {
                CurrentWaterLabel.setText(String.valueOf(w));  
                CurrentWaterLabel.setForeground(Color.green);
            }else{
                CurrentTempLabel.setText(String.valueOf(t));
                CurrentTempLabel.setForeground(Color.red);
            }
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ChangeOptimalButton;
    private javax.swing.JButton CreateReportButton;
    private javax.swing.JLabel CurrentConditionsLabel;
    private javax.swing.JLabel CurrentHumidityLabel;
    private javax.swing.JLabel CurrentLightLabel;
    private javax.swing.JLabel CurrentTempLabel;
    private javax.swing.JLabel CurrentWaterLabel;
    private javax.swing.JLabel HumidityLabel;
    private javax.swing.JLabel LightLabel;
    private javax.swing.JLabel LiveFeedLabel;
    private javax.swing.JPanel LiveFeedPanel;
    private javax.swing.JPanel PanelA;
    private javax.swing.JPanel PanelB;
    private javax.swing.JPanel PanelC;
    private javax.swing.JLabel TempLabel;
    private javax.swing.JLabel WaterLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
