/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gem;

import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Nirda
 */
public class Setup extends javax.swing.JFrame {

    /**
     * Creates new form Setup
     */
    public Setup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        PanelA = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        humidityLabel = new javax.swing.JLabel();
        lightLabel = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        waterintervalLabel = new javax.swing.JLabel();
        setButton = new javax.swing.JButton();
        seperator1 = new javax.swing.JSeparator();
        seperator2 = new javax.swing.JSeparator();
        seperator3 = new javax.swing.JSeparator();
        seperator4 = new javax.swing.JSeparator();
        seperator5 = new javax.swing.JSeparator();
        temperatureField = new javax.swing.JTextField();
        humidityField = new javax.swing.JTextField();
        lightField = new javax.swing.JTextField();
        watertimeField = new javax.swing.JTextField();
        waterintervalField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelA.setBackground(new java.awt.Color(36, 47, 65));

        titleLabel.setBackground(new java.awt.Color(36, 47, 65));
        titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(204, 204, 204));
        titleLabel.setText("Set Optimal Conditions");

        temperatureLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        temperatureLabel.setForeground(new java.awt.Color(204, 204, 204));
        temperatureLabel.setText("Temperature");

        humidityLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        humidityLabel.setForeground(new java.awt.Color(204, 204, 204));
        humidityLabel.setText("Humidity");

        lightLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lightLabel.setForeground(new java.awt.Color(204, 204, 204));
        lightLabel.setText("Light Level");

        waterLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        waterLabel.setForeground(new java.awt.Color(204, 204, 204));
        waterLabel.setText("Water Time (seconds)");

        waterintervalLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        waterintervalLabel.setForeground(new java.awt.Color(204, 204, 204));
        waterintervalLabel.setText("Water Interval (seconds)");

        setButton.setBackground(new java.awt.Color(204, 204, 204));
        setButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        setButton.setText("Set");
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        temperatureField.setBackground(new java.awt.Color(36, 47, 65));
        temperatureField.setForeground(new java.awt.Color(255, 255, 255));
        temperatureField.setBorder(null);
        temperatureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureFieldActionPerformed(evt);
            }
        });

        humidityField.setBackground(new java.awt.Color(36, 47, 65));
        humidityField.setForeground(new java.awt.Color(255, 255, 255));
        humidityField.setBorder(null);
        humidityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                humidityFieldActionPerformed(evt);
            }
        });

        lightField.setBackground(new java.awt.Color(36, 47, 65));
        lightField.setForeground(new java.awt.Color(255, 255, 255));
        lightField.setBorder(null);

        watertimeField.setBackground(new java.awt.Color(36, 47, 65));
        watertimeField.setForeground(new java.awt.Color(255, 255, 255));
        watertimeField.setBorder(null);

        waterintervalField.setBackground(new java.awt.Color(36, 47, 65));
        waterintervalField.setForeground(new java.awt.Color(255, 255, 255));
        waterintervalField.setBorder(null);

        javax.swing.GroupLayout PanelALayout = new javax.swing.GroupLayout(PanelA);
        PanelA.setLayout(PanelALayout);
        PanelALayout.setHorizontalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelALayout.createSequentialGroup()
                .addGroup(PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(humidityField, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(PanelALayout.createSequentialGroup()
                            .addGap(105, 105, 105)
                            .addGroup(PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lightLabel)
                                .addComponent(waterLabel)
                                .addComponent(waterintervalLabel)
                                .addComponent(seperator2)
                                .addComponent(seperator3)
                                .addComponent(seperator4)
                                .addComponent(seperator5)
                                .addComponent(seperator1)
                                .addComponent(temperatureLabel)
                                .addComponent(temperatureField)
                                .addComponent(humidityLabel)
                                .addComponent(lightField)
                                .addComponent(watertimeField)
                                .addComponent(waterintervalField, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))))
                    .addGroup(PanelALayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelALayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(titleLabel)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        PanelALayout.setVerticalGroup(
            PanelALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelALayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(titleLabel)
                .addGap(44, 44, 44)
                .addComponent(temperatureLabel)
                .addGap(4, 4, 4)
                .addComponent(temperatureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humidityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(humidityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(seperator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(seperator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waterLabel)
                .addGap(4, 4, 4)
                .addComponent(watertimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seperator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waterintervalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waterintervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(seperator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(setButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void temperatureFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void humidityFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String user = CreateAccount.getUsername();
        try {
            if (Float.valueOf(temperatureField.getText())> 0 & Float.valueOf(humidityField.getText())> 0 & Integer.valueOf(lightField.getText())> 0 )
            {
                String query = "INSERT INTO optimal_conditions (Username,Optimal_Temperature,Optimal_Humidity,Optimal_LightLevel,Optimal_WaterTime,Optimal_WaterTimeInterval) VALUES ('"+user+"','" + temperatureField.getText() +"','" + humidityField.getText() +"','" + lightField.getText()+"','" + watertimeField.getText()+"','" + waterintervalField.getText() +"');";
                boolean rs1 = LinkJavaMySQL.insertQuery(query);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Setup.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose();
        new Login().setVisible(true);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel PanelA;
    private javax.swing.JTextField humidityField;
    private javax.swing.JLabel humidityLabel;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField lightField;
    private javax.swing.JLabel lightLabel;
    private javax.swing.JSeparator seperator1;
    private javax.swing.JSeparator seperator2;
    private javax.swing.JSeparator seperator3;
    private javax.swing.JSeparator seperator4;
    private javax.swing.JSeparator seperator5;
    private javax.swing.JButton setButton;
    private javax.swing.JTextField temperatureField;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JTextField waterintervalField;
    private javax.swing.JLabel waterintervalLabel;
    private javax.swing.JTextField watertimeField;
    // End of variables declaration                   
}
